inherit_gem:
  mad_rubocop: .rubocop.yml

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: compact

# Disabled, not a Rails project and don't have access to Rails' logging.
Rails/Output:
  Enabled: false
