/**
 * This file is auto-generated by widget-post-message-definitions,
 * DO NOT EDIT.
 *
 * If you need to make changes to the code in this file, you can do so by
 * modifying the definitions found in the widget-post-message-definitions
 * project.
 */

export enum Type {
  Load = "mx/load",
  Ping = "mx/ping",
  Focustrap = "mx/focusTrap",
  ConnectLoaded = "mx/connect/loaded",
  ConnectEntercredentials = "mx/connect/enterCredentials",
  ConnectInstitutionsearch = "mx/connect/institutionSearch",
  ConnectSelectedinstitution = "mx/connect/selectedInstitution",
  ConnectMemberconnected = "mx/connect/memberConnected",
  ConnectConnectedPrimaryaction = "mx/connect/connected/primaryAction",
  ConnectMemberdeleted = "mx/connect/memberDeleted",
  ConnectCreatemembererror = "mx/connect/createMemberError",
  ConnectMemberstatusupdate = "mx/connect/memberStatusUpdate",
  ConnectOautherror = "mx/connect/oauthError",
  ConnectOauthrequested = "mx/connect/oauthRequested",
  ConnectStepchange = "mx/connect/stepChange",
  ConnectSubmitmfa = "mx/connect/submitMFA",
  ConnectUpdatecredentials = "mx/connect/updateCredentials",
  PulseLoad = "mx/pulse/load",
  PulseOverdraftwarningCtaTransferfunds = "mx/pulse/overdraftWarning/cta/transferFunds",
  AccountCreated = "mx/account/created",
}

export const typeLookup: Record<string, Type> = {
  [Type.Load]: Type.Load,
  [Type.Ping]: Type.Ping,
  [Type.Focustrap]: Type.Focustrap,
  "mx/focustrap": Type.Focustrap,
  [Type.ConnectLoaded]: Type.ConnectLoaded,
  [Type.ConnectEntercredentials]: Type.ConnectEntercredentials,
  "mx/connect/entercredentials": Type.ConnectEntercredentials,
  [Type.ConnectInstitutionsearch]: Type.ConnectInstitutionsearch,
  "mx/connect/institutionsearch": Type.ConnectInstitutionsearch,
  [Type.ConnectSelectedinstitution]: Type.ConnectSelectedinstitution,
  "mx/connect/selectedinstitution": Type.ConnectSelectedinstitution,
  [Type.ConnectMemberconnected]: Type.ConnectMemberconnected,
  "mx/connect/memberconnected": Type.ConnectMemberconnected,
  [Type.ConnectConnectedPrimaryaction]: Type.ConnectConnectedPrimaryaction,
  "mx/connect/connected/primaryaction": Type.ConnectConnectedPrimaryaction,
  [Type.ConnectMemberdeleted]: Type.ConnectMemberdeleted,
  "mx/connect/memberdeleted": Type.ConnectMemberdeleted,
  [Type.ConnectCreatemembererror]: Type.ConnectCreatemembererror,
  "mx/connect/createmembererror": Type.ConnectCreatemembererror,
  [Type.ConnectMemberstatusupdate]: Type.ConnectMemberstatusupdate,
  "mx/connect/memberstatusupdate": Type.ConnectMemberstatusupdate,
  [Type.ConnectOautherror]: Type.ConnectOautherror,
  "mx/connect/oautherror": Type.ConnectOautherror,
  [Type.ConnectOauthrequested]: Type.ConnectOauthrequested,
  "mx/connect/oauthrequested": Type.ConnectOauthrequested,
  [Type.ConnectStepchange]: Type.ConnectStepchange,
  "mx/connect/stepchange": Type.ConnectStepchange,
  [Type.ConnectSubmitmfa]: Type.ConnectSubmitmfa,
  "mx/connect/submitmfa": Type.ConnectSubmitmfa,
  [Type.ConnectUpdatecredentials]: Type.ConnectUpdatecredentials,
  "mx/connect/updatecredentials": Type.ConnectUpdatecredentials,
  [Type.PulseLoad]: Type.PulseLoad,
  [Type.PulseOverdraftwarningCtaTransferfunds]: Type.PulseOverdraftwarningCtaTransferfunds,
  "mx/pulse/overdraftwarning/cta/transferfunds": Type.PulseOverdraftwarningCtaTransferfunds,
  [Type.AccountCreated]: Type.AccountCreated,
}


export type LoadPayload = {
  type: Type.Load,
}

export type PingPayload = {
  type: Type.Ping,
  user_guid: string,
  session_guid: string,
}

export type FocustrapPayload = {
  type: Type.Focustrap,
  user_guid: string,
  session_guid: string,
}

export type ConnectLoadedPayload = {
  type: Type.ConnectLoaded,
  user_guid: string,
  session_guid: string,
  initial_step: "search" | "selectMember" | "enterCreds" | "mfa" | "connected" | "loginError" | "disclosure",
}

export type ConnectEntercredentialsPayload = {
  type: Type.ConnectEntercredentials,
  user_guid: string,
  session_guid: string,
  institution: { code: string, guid: string },
}

export type ConnectInstitutionsearchPayload = {
  type: Type.ConnectInstitutionsearch,
  user_guid: string,
  session_guid: string,
  query: string,
}

export type ConnectSelectedinstitutionPayload = {
  type: Type.ConnectSelectedinstitution,
  user_guid: string,
  session_guid: string,
  code: string,
  guid: string,
  name: string,
  url: string,
}

export type ConnectMemberconnectedPayload = {
  type: Type.ConnectMemberconnected,
  user_guid: string,
  session_guid: string,
  member_guid: string,
}

export type ConnectConnectedPrimaryactionPayload = {
  type: Type.ConnectConnectedPrimaryaction,
  user_guid: string,
  session_guid: string,
}

export type ConnectMemberdeletedPayload = {
  type: Type.ConnectMemberdeleted,
  user_guid: string,
  session_guid: string,
  member_guid: string,
}

export type ConnectCreatemembererrorPayload = {
  type: Type.ConnectCreatemembererror,
  user_guid: string,
  session_guid: string,
  institution_guid: string,
  institution_code: string,
}

export type ConnectMemberstatusupdatePayload = {
  type: Type.ConnectMemberstatusupdate,
  user_guid: string,
  session_guid: string,
  member_guid: string,
  connection_status: number,
}

export type ConnectOautherrorPayload = {
  type: Type.ConnectOautherror,
  user_guid: string,
  session_guid: string,
  member_guid: string,
}

export type ConnectOauthrequestedPayload = {
  type: Type.ConnectOauthrequested,
  user_guid: string,
  session_guid: string,
  url: string,
  member_guid: string,
}

export type ConnectStepchangePayload = {
  type: Type.ConnectStepchange,
  user_guid: string,
  session_guid: string,
  previous: string,
  current: string,
}

export type ConnectSubmitmfaPayload = {
  type: Type.ConnectSubmitmfa,
  user_guid: string,
  session_guid: string,
  member_guid: string,
}

export type ConnectUpdatecredentialsPayload = {
  type: Type.ConnectUpdatecredentials,
  user_guid: string,
  session_guid: string,
  member_guid: string,
  institution: { code: string, guid: string },
}

export type PulseLoadPayload = {
  type: Type.PulseLoad,
}

export type PulseOverdraftwarningCtaTransferfundsPayload = {
  type: Type.PulseOverdraftwarningCtaTransferfunds,
  account_guid: string,
  amount: number,
}

export type AccountCreatedPayload = {
  type: Type.AccountCreated,
  guid: string,
}


export type WidgetPayload =
  | LoadPayload
  | PingPayload
  | FocustrapPayload
  | ConnectLoadedPayload
  | ConnectEntercredentialsPayload
  | ConnectInstitutionsearchPayload
  | ConnectSelectedinstitutionPayload
  | ConnectMemberconnectedPayload
  | ConnectConnectedPrimaryactionPayload
  | ConnectMemberdeletedPayload
  | ConnectCreatemembererrorPayload
  | ConnectMemberstatusupdatePayload
  | ConnectOautherrorPayload
  | ConnectOauthrequestedPayload
  | ConnectStepchangePayload
  | ConnectSubmitmfaPayload
  | ConnectUpdatecredentialsPayload
  | PulseLoadPayload
  | PulseOverdraftwarningCtaTransferfundsPayload

export type EntityPayload =
  | AccountCreatedPayload

export type Payload =
  | WidgetPayload
  | EntityPayload
