name: Build TypeScript Package

on:
  pull_request:
    paths:
    - packages/typescript/**
    - .github/workflows/build-typescript-package.yml
  push:
    branches:
    - master

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm
        cache-dependency-path: packages/typescript/package-lock.json
    - uses: actions/cache@v3
      with:
        path: packages/typescript/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('packages/typescript/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm install
      working-directory: packages/typescript

    - run: npm run prettier -- --check
      working-directory: packages/typescript

    - run: npm run lint
      working-directory: packages/typescript

    - run: npm run build
      working-directory: packages/typescript

    - run: npm run test
      working-directory: packages/typescript
