name: Build Swift Package

on:
  pull_request:
    paths:
    - packages/swift/**
    - .github/workflows/build-swift-package.yml
  push:
    branches:
    - master

jobs:
  Build:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: packages/swift/.build
        key: ${{ runner.os }}-spm-${{ hashFiles('packages/swift/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - run: swift build
      working-directory: packages/swift

    - run: swift test
      working-directory: packages/swift
